### ISSUE TITLE
Doc annotations overlaps add annotation text box

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#4136] opened 2017-10-23 05:16 UTC
![screenshot from 2017-10-23 10-44-32](https://user-images.githubusercontent.com/7681361/31873198-595d2260-b7df-11e7-9391-cd1907ce8251.png)

**Comment by NatashaWso2** [comment] 2017-11-17 05:22
Duplicate of #4214, hence this issue can be closed

**Closed by NatashaWso2** 2017-11-17 05:22 UTC
Labels: 0.94-pre-release, Priority/High, Severity/Minor
