### ISSUE TITLE
[Bug][Intermittent][Editor] JS script error intermittently

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#136] opened 2017-02-09 13:16 UTC
<a href="https://github.com/yasassri"><img src="https://avatars.githubusercontent.com/u/7681361?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Tuesday Jan 24, 2017 at 04:04 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/975_

----

I'm on Firefox 50.1.0
![screenshot from 2017-01-24 09-30-22](https://cloud.githubusercontent.com/assets/7681361/22233696/05306dac-e218-11e6-860d-b4d8ac8c3eda.png)

**Comment by hevayo** [comment] 2017-06-04 05:50
I was unable to reproduce this issue with our latest version, Also the implementation has changed a lot from the mention version. Hence closing the issue please reopen if observe again.

**Closed by hevayo** 2017-06-04 05:50 UTC
Labels: Imported
