### ISSUE TITLE
[Important!]Action invoke is broken when there is a lot of connectors in a service

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#124] opened 2017-02-09 13:16 UTC
<a href="https://github.com/srsharon"><img src="https://avatars.githubusercontent.com/u/10986966?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [srsharon](https://github.com/srsharon)**
_Monday Jan 23, 2017 at 07:07 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/929_

----

![image](https://cloud.githubusercontent.com/assets/10986966/22194420/5d7722c2-e168-11e6-96c5-88736c9e93de.png)

**Comment by jeradrutnam** [comment] 2017-02-27 06:54
Couldn't reproduce in the latest pack

**Comment by nadeeshaan** [comment] 2017-03-03 06:47
Closing based on the above comment

**Closed by nadeeshaan** 2017-03-03 06:47 UTC
Labels: Blocker, bug, Imported
