### ISSUE TITLE
Try-it is not supported for Web socket

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4501] opened 2017-11-06 03:05 UTC
Try-it option is available for WS sample. But when try to use it no services are shown. This should be disabled for WS
![52](https://user-images.githubusercontent.com/1845370/32423598-3e4dc508-c2cd-11e7-97bd-65cc44330423.png)

**Comment by hemikak** [comment] 2017-11-06 06:50
This is a duplicate of https://github.com/ballerinalang/composer/issues/4091 , 
Hence closing.

**Closed by hemikak** 2017-11-06 06:50 UTC
Labels: 0.95, Priority/Highest, Severity/Critical, Type/Bug
