### ISSUE TITLE
Moving to source view automatically when drag and drop elements on to the canvas

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2713] opened 2017-08-11 05:47 UTC
Release - 0.91.1 (nightly build 08/11)

**Steps**
1. Add a service
2. Add a fork-join to the service
3. Add a worker
4. Add a if-condition to the worker (Automatically moving to source view)
5. Add another if-condition
6. Delete it (Automatically moving to source view)

![f1](https://user-images.githubusercontent.com/1845370/29202510-7ded5c4a-7e86-11e7-96bf-e972bcf3cf42.png)

**Issue**
Automatically moving to source view at step 4 and 6

**Comment by kaviththiranga** [comment] 2017-08-11 06:24
This is due to a parser error which prevents having fork-join & workers both at same function same time.
https://github.com/ballerinalang/ballerina/issues/2917
Due to the parser error composer automatically moves to source view. However, since there is no syntax errors, it doesn't popup the error notification to let user know why it moved source view automatically.
From composer side, we can do a fix by displaying a generic notification saying there was an error with parser etc, and had to move to source view. However, to solve the root cause, a fix is needed on parser side.

**Comment by NatashaWso2** [comment] 2017-11-24 08:24
This is fixed in the latest master, hence this issue can be closed.

**Closed by NatashaWso2** 2017-11-24 08:24 UTC
Labels: Priority/High, Severity/Minor, Type/Bug
