### ISSUE TITLE
Support else-if

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#498] opened 2017-02-12 14:16 UTC
else-if and statements without else block is not supported.

E.g. : 
    if (stone && value) {
        result = true;
    } else if (value && stone) {
        result = true;
    } else if (value || !stone) {
        result =  false;
    } else if (!stone || !value) {
        result =  false;
    } else if (stone || !value) {
        result =  false;
    }

https://github.com/ballerinalang/ballerina/blob/master/modules/ballerina-core/src/test/resources/lang/expressions/binary-expr.bal

**Comment by nadeeshaan** [comment] 2017-05-22 12:44
Duplicate of #137 Hence closing

**Closed by nadeeshaan** 2017-05-22 12:44 UTC
Labels: enhancement
