### ISSUE TITLE
Null displayed for data types when debugging

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4022] opened 2017-10-19 13:12 UTC
![18](https://user-images.githubusercontent.com/1845370/31772376-1afa6bc0-b4fd-11e7-95a9-8234b226c5a8.png)

**Comment by pahans** [comment] 2017-10-24 16:06
duplicate of https://github.com/ballerinalang/composer/issues/3002

**Closed by pahans** 2017-10-24 16:06 UTC
Labels: 0.94-pre-release, Debugger, Priority/High, Severity/Major, Type/Bug
