### ISSUE TITLE
Home page crashing on Chome (Version 63.0.3239.84)

### ISSUE THREAD

**Issue by SupunS** [ballerinalang/composer#4993] opened 2018-01-24 06:08 UTC
**Description:**
Downloaded ballerina-tools-0.95.7 (latest available)
I am on Chrome Version 63.0.3239.84 (Official Build) (64-bit)

Home page is crashing with following.
<img width="1349" alt="composer" src="https://user-images.githubusercontent.com/7834839/35317073-ffd80e52-00fa-11e8-9499-adba6bf88ca3.png">

works fine on Firefox (57.0.3 (64-bit)).

**Affected Product Version:**
0.95.7

**Related Issues:**
Created this to track https://github.com/ballerinalang/ballerina/issues/4455

**Comment by kaviththiranga** [comment] 2018-01-24 06:57
@sumedharubasinghe 
Root cause was due to - not resetting cache IDs for some of the new asset builds (fixed with https://github.com/ballerinalang/composer/pull/4984) and re-using same history key (a local storage value) for new split view implementation (fixed with https://github.com/ballerinalang/composer/pull/4980)

**Closed by kaviththiranga** 2018-01-24 06:57 UTC
