### ISSUE TITLE
[WS-Sample] Try it given for the Web socket sample

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#4459] opened 2017-11-05 09:30 UTC
Since the sample cannot be invoked by the plain try it, its better to remove the link given to the try it when the sample is deployed. Else if the link is given, then the try it should work as a client to invoke the WS service.

**Comment by hemikak** [comment] 2017-11-09 10:05
Duplicate of https://github.com/ballerinalang/composer/issues/4091

**Closed** 2017-11-09 11:42 UTC
Labels: 0.95, Priority/High, Resolution/Duplicate
