### ISSUE TITLE
[Content Assist] No suggestions when trying to retrieve the properties of structs

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3278] opened 2017-10-04 09:45 UTC
Release 0.93

Sample: https://ballerinalang.org/docs/by-example/datatables

Try the following in the sample. No suggestions are given
`rs.id`

**Comment by NatashaWso2** [comment] 2017-11-22 06:22
This is a duplicate of #3616, hence this issue can be closed

**Closed by NatashaWso2** 2017-11-22 06:22 UTC
Labels: Content Assist, Priority/Normal, Severity/Major, Type/Bug
