### ISSUE TITLE
Cannot scroll down beyond some point when the console is open

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#1003] opened 2017-02-19 22:08 UTC
1. Write a lengthy code
2. Open the console

Issue
You won't be able to scroll down beyond some point
![scroll](https://cloud.githubusercontent.com/assets/1845370/23107156/f7c8a920-f71d-11e6-8848-313e743ce637.png)

**Comment by hevayo** [comment] 2017-06-04 15:42
Duplicate of #1664 closing this issue since above is new.

**Closed by hevayo** 2017-06-04 15:42 UTC
Labels: bug, Design-View
