### ISSUE TITLE
Functions in same packages are not identified

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3889] opened 2017-10-17 06:01 UTC
![screenshot from 2017-10-17 11-30-03](https://user-images.githubusercontent.com/7681361/31649051-a58173fe-b32e-11e7-9c6d-69b36e94405d.png)

**Comment by NatashaWso2** [comment] 2017-11-20 06:03
This is a duplicate of #4028, hence closing this issue.

**Closed by NatashaWso2** 2017-11-20 06:03 UTC
Labels: 0.94-pre-release, Priority/Highest, Severity/Critical
