### ISSUE TITLE
Cannot debug multiple services

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3498] opened 2017-10-11 06:23 UTC
I have 3 services all linked together. Service 1 calls Service 2 and then Service 3. Add debug points in service 2 and 3 and start debugging.

**Issue**
The debug point is hit, but when step in, the movement of the execution is not displayed which makes it unusable.

**Comment by pahans** [comment] 2017-11-23 08:30
duplicate of https://github.com/ballerinalang/composer/issues/2974

**Closed by pahans** 2017-11-23 08:30 UTC
Labels: Debugger, Priority/High, Severity/Blocker, Type/Bug
