### ISSUE TITLE
Deleting ballerina samples

### ISSUE THREAD

**Issue by jeradrutnam** [ballerinalang/composer#1832] opened 2017-06-09 08:28 UTC
![image](https://user-images.githubusercontent.com/7569427/26966863-799ee378-4d19-11e7-84df-cde9f8ff04ec.png)

![image](https://user-images.githubusercontent.com/7569427/26967227-1b98ae24-4d1b-11e7-9e23-da40b17215b4.png)

Since we are having samples listing on welcome page. What if we not allow deleting samples? Because it will affect the welcome page. 

So we will only have a remove option for samples.

![image](https://user-images.githubusercontent.com/7569427/26967273-3eb3775e-4d1b-11e7-9f60-2804fb31aa2f.png)

**Comment by hevayo** [comment] 2017-06-22 08:35
We decided to asked for a directory location when opening a packaged sample and copy the sample there and open the copy. This will make sure the samples will not get changed by the user.

**Comment by hevayo** [comment] 2017-10-21 08:17
closing since a duplicate of https://github.com/ballerinalang/composer/issues/1915

**Closed by hevayo** 2017-10-21 08:17 UTC
