### ISSUE TITLE
[feature request] ability export the design view content as a PDF or some type of image file

### ISSUE THREAD

**Issue by handakumbura** [ballerinalang/composer#2018] opened 2017-06-19 09:01 UTC
It would be useful if the design view content can be exported as a PDF or some type of image file. The export option can be given at file level, service level or resource level. In the case of service level and resource level, the option can be given as part of the tittle bar(along with minimize and remove options).

**Comment by hevayo** [comment] 2017-06-22 10:21
Duplicate of https://github.com/ballerinalang/composer/issues/74

**Closed by hevayo** 2017-06-22 10:21 UTC

**Comment by handakumbura** [comment] 2017-06-22 10:27
Ack.
