### ISSUE TITLE
Incompleted assignment statement get reset when switched to another window and back

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#1966] opened 2017-06-14 05:42 UTC
_Build: ballerinalang/tools-distribution/org.ballerinalang.tools:ballerina-tools: 378_

**Steps**
1. Drag and drop an assignment statement
2. Complete the left hand side
3. While completing the right hand side switch to another window

**Actual behaviour**: When switched back to the composer, the half way written right side is reset

**Expected behaviour**: The half way written right statement should be preserved.

**Comment by nadeeshaan** [comment] 2017-09-08 08:41
This is by design at the moment. We do not keep track of the intermediate state and preserve them. We only validate and preserve the statement content on focus out. Hence removing the Label, Bug and adding as an usability improvement

**Comment by nadeeshaan** [comment] 2017-10-30 05:51
Closing the issue, since this is by design as mentioned earlier

**Closed by nadeeshaan** 2017-10-30 05:51 UTC
Labels: Design-View, Type/Improvement
