### ISSUE TITLE
[Action view] Doesn't compact the code but compacts the design

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#4469] opened 2017-11-05 10:18 UTC
As shown in the below image, the design is compacted, but not the source when action view is triggered

![com_0 95_new_5](https://user-images.githubusercontent.com/15624590/32413895-c9eb7cf0-c240-11e7-8ab2-58891710190e.png)

**Comment by nadeeshaan** [comment] 2017-11-24 09:01
Perspectives are only for the design view. This is by design and hence closing the issue

**Closed by nadeeshaan** 2017-11-24 09:01 UTC
Labels: 0.95, Priority/High
