### ISSUE TITLE
Syntax error in default code generated when http functions dropped in

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#4410] opened 2017-11-04 03:58 UTC
As shown in the below image, there is a syntax error in the generated code when dropped in. 

Sample code
```
var var1 = requestRef.getStringPayload();
```
The reference should be similar to what is defined when initializing the service and the default generated code should not have errors

![com_0 95_1](https://user-images.githubusercontent.com/15624590/32402081-7371e61a-c142-11e7-9ade-03b4169b7b84.png)

**Comment by nadeeshaan** [comment] 2017-11-06 09:22
This particular case is due to the following reason. 
Functions such as getStringPayload are bound to a struct. So when a user drags and drops such a function, we do not create an empty struct and then use that against the method. What we do is, we generate a temp reference allowing the user to change as wish. In order to avoid the user being confused, we show the semantic error where the user can identify and do the changes accordingly.

Closing the issue, since this has been done by design

**Closed by nadeeshaan** 2017-11-06 09:22 UTC
Labels: 0.95, Priority/Highest, Severity/Critical
