### ISSUE TITLE
Action buttons not get removed from the canvas once collapse the panes

### ISSUE THREAD

**Issue by dakshika** [ballerinalang/composer#5012] opened 2018-01-29 06:14 UTC
**Description:**
$subject 

**Affected Product Version:**
0.96.0

**OS, DB, other environment details and versions:**    
Linux 16.04 / Chrome latest 

**Steps to reproduce:**
1. Add function to screen
2. collapse the function pane
![panecollapse](https://user-images.githubusercontent.com/6497326/35495948-bd24b4f0-04e9-11e8-9218-b7acb4dcc117.png)
![panecollapse2](https://user-images.githubusercontent.com/6497326/35495949-bd5efb88-04e9-11e8-9b49-8eb1b1dd32b9.png)

**Comment by DimalChandrasiri** [comment] 2018-01-29 07:49
Possible duplicate of #4922 Bug

**Comment by keizer619** [comment] 2018-01-29 11:37
Yes its same issue, hence closing this issue

**Closed by keizer619** 2018-01-29 11:37 UTC
Labels: Type/Bug
