### ISSUE TITLE
Tool palette search feature should search package names as well

### ISSUE THREAD

**Issue by sumuditha-viraj** [ballerinalang/composer#2218] opened 2017-06-30 10:08 UTC
Currently tool palette search searches only for the tool items(functions, connectors, connector actions etc.). It will be very useful if we can search packages by the search query string. For an example I need to search for twitter package from the lengthy package list. But this will not list twitter package for "twitter" query string

<img width="253" alt="screen shot 2017-06-30 at 3 32 49 pm" src="https://user-images.githubusercontent.com/6814264/27731120-67ee74d6-5da9-11e7-8ffd-0f28cfbfd38c.png">

**Comment by pahans** [comment] 2017-07-24 09:41
duplicate of https://github.com/ballerinalang/composer/issues/1998

**Closed by pahans** 2017-07-24 09:41 UTC
Labels: Enhancement, Tool-Palette
