### ISSUE TITLE
[Lang Server] auto import unused imports during selection from suggestions

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2392] opened 2017-07-17 09:16 UTC
When a package that is not imported suggested from lang server, on hit of enter, can we auto import it? This is similar to function drag drop from design view.

**Comment by NatashaWso2** [comment] 2017-11-14 04:05
Duplicate of #2445
Hence closing the issue

**Closed by NatashaWso2** 2017-11-14 04:05 UTC
Labels: Type/Improvement
