### ISSUE TITLE
Cannot connect to service level connectors from workers

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2711] opened 2017-08-11 05:21 UTC
Release 0.91.1

![w1](https://user-images.githubusercontent.com/1845370/29202140-b1105a0e-7e82-11e7-9a0e-d4deba9b5a19.png)
![w2](https://user-images.githubusercontent.com/1845370/29202139-b0c90c80-7e82-11e7-99a8-d779f9643a4a.png)
![w3](https://user-images.githubusercontent.com/1845370/29202165-f0f4a1ca-7e82-11e7-9d96-f1decbede90d.png)

**Comment by NatashaWso2** [comment] 2017-08-15 13:11
This cannot be reproduced in the latest pack 0.92
Service level connectors can be invoked using resource level worker invocations. 
![serviceconne2](https://user-images.githubusercontent.com/13446645/29317373-3c4d266a-81e9-11e7-9036-6c0cf8004df5.png)
![servicelevelconnectors1](https://user-images.githubusercontent.com/13446645/29317374-3c4dbd3c-81e9-11e7-89b1-26155e048e78.png)

**Comment by NatashaWso2** [comment] 2017-08-15 13:11
This issue can be closed since its fixed in the latest pack 0.922

**Closed** 2017-08-15 13:13 UTC
Labels: Bug, Priority:High, Severity:Major
