### ISSUE TITLE
[Editor]When defining a lengthy name as resource name, resource name and operations overlap on each other Check the attachment

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#230] opened 2017-02-09 13:20 UTC
<a href="https://github.com/gvasanka"><img src="https://avatars.githubusercontent.com/u/3368635?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gvasanka](https://github.com/gvasanka)**
_Wednesday Feb 01, 2017 at 11:43 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1230_

----

Steps:
1.Open the provided bal file on Editor (loaded on Chrome Browser)
Note: Renamed .bal to .txt since github doesn't allow to upload bal files

Issue:
When defining a lengthy name as resource name, resource name and operations overlap on each other
Check the attachment

[TestStatusCode.txt](https://github.com/wso2/ballerina/files/744688/TestStatusCode.txt)
![selection_147](https://cloud.githubusercontent.com/assets/3368635/22505478/bcf2ac54-e8a1-11e6-8323-6a2828f1e498.png)

**Comment by nadeeshaan** [comment] 2017-04-17 07:28
Closing hence the issue is resolved and fix is merged

**Closed by nadeeshaan** 2017-04-17 07:28 UTC
Labels: Blocker, Imported
