### ISSUE TITLE
Code re-formatting not working properly

### ISSUE THREAD

**Issue by dakshika** [ballerinalang/composer#1923] opened 2017-06-12 06:34 UTC
tested code:

function testNullInForkJoin () (message, message) {
    message m = null;
fork {    worker foo {
        message resp1 = null;
        resp1 ->fork;
    }
    worker bar {
        message resp2 = {};
        resp2 ->fork;
    }
}
join (all ) (map allReplies){
}
timeout (30000) (map msgs){
    return null,null;
}
}

**Comment by maheeka** [comment] 2017-06-13 11:22
The issue is in capturing default whitespaces in fork join

**Comment by kaviththiranga** [comment] 2017-06-13 11:26
Yeah, we need to fix whitespace handling in jork-join source gen. @manuranga Please note.

**Comment by manuranga** [comment] 2017-06-29 17:54
fixed in 99ec1c8b

**Closed** 2017-06-29 17:54 UTC
