### ISSUE TITLE
Console covers the code in the source view

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerinalang/composer#1297] opened 2017-03-28 05:49 UTC
Consider the below scenario. In the below image, part of the program code is covered by the console window and there is no scroll bar to view the covered part of the code.

![bug](https://cloud.githubusercontent.com/assets/6178058/24390703/41c10c24-13a8-11e7-8dd6-0063f0f35e5a.jpeg)

**Comment by hevayo** [comment] 2017-06-04 15:41
duplicate of #1664 closing this since above issue is new

**Closed by hevayo** 2017-06-04 15:41 UTC
Labels: bug
