### ISSUE TITLE
Invalid snapshots of sample images

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4403] opened 2017-11-04 03:02 UTC
Wrong syntax and does not include latest UI changes
![1](https://user-images.githubusercontent.com/1845370/32401704-7467d2e4-c13a-11e7-8f04-b1591987703b.png)

**Comment by hevayo** [comment] 2018-01-02 06:49
Duplicate of  https://github.com/ballerinalang/composer/issues/4903

**Closed by hevayo** 2018-01-02 06:49 UTC
Labels: 0.95, Priority/Highest, Severity/Minor, Type/Bug
