### ISSUE TITLE
Mappings are not deleted when the statements inside transform are deleted

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3606] opened 2017-10-12 11:19 UTC
1. In the split view, delete all the statements inside the transform block

**Issue**
Mappings are not deleted when the statements inside transform are deleted

**Comment by maheeka** [comment] 2017-10-16 18:44
@dilinisg Is there a specific sample where you observed this issue? We are not able to reproduce this.

**Comment by keizer619** [comment] 2017-11-16 08:59
Cannot reproduce in 0.95 release, hence closing the issue.

**Closed by keizer619** 2017-11-16 08:59 UTC
Labels: 0.94-pre-release, Priority/High, Severity/Major, Transform Stmt, Type/Bug
