### ISSUE TITLE
Improve the file explorer

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2949] opened 2017-08-29 05:42 UTC
Current file explorer which is used to open files, save files etc. is not very user friendly. It takes too much effort where we have to expand, scroll down, again expand, scroll down when the path is long. Also, it is very difficult to find a directory as well. I have also seen people keep the path copied somewhere and paste it when they need to use this functionality.

Temporary solution: Set the default location to the user home instead of the root path.

**Comment by NatashaWso2** [comment] 2017-11-20 08:28
This is a duplicate of #4306 , hence closing this issue

**Closed by NatashaWso2** 2017-11-20 08:28 UTC
Labels: Priority/High, Type/Improvement
