### ISSUE TITLE
Importing a custom package breaks the design view

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#4217] opened 2017-10-27 09:47 UTC
Browser: Chrome Version 62.0.3202.62 (Official Build) (64-bit)

**Sample code**
```
import org.wso2.ballerina.connectors.testConn;
import ballerina.net.http;
import ballerina.utils;

@http:configuration {
    basePath:"/integrate"
}
service<http> service1 {
    @http:resourceConfig {
        methods:["POST"],
        path:"/get"
    }
    resource echo (http:Request req,http:Response res) {
       
    }
}
```
When the above code is opened following observations are given

1. Design view has nothing in split view
2. When source view is loaded cannot go back to design view

When the custom package is typed in source view, it was observed that it dissapears.

**Comment by maheeka** [comment] 2017-10-30 06:03
Root cause is reported in https://github.com/ballerinalang/composer/issues/4241. Hence closing.

**Closed by maheeka** 2017-10-30 06:03 UTC
Labels: 0.94-M1, Priority/Highest, Severity/Blocker
