### ISSUE TITLE
Debug points of workers are not honoured

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2979] opened 2017-08-31 12:11 UTC
Release 0.93

Debug points of workers are not honoured at all.

1. Add debug points inside worker: addition and debug the program
```
import ballerina.lang.system;

function main (string[] args) {
    int i1 = 5;
    int i2 = 10;
    int ans = 0;
    i1,i2 -> addition;
    system:println("sent");
    ans <- addition;
    worker addition {
        int a = 0;
        int b = 0;
        a,b <- default;
        int sum = a + b;
        system:println("sum = " + sum);
        sum -> default;
    }
}
```

**Comment by pahans** [comment] 2017-10-20 09:07
duplicate of https://github.com/ballerinalang/composer/issues/2981

**Closed by pahans** 2017-10-20 09:07 UTC
Labels: Debugger, Priority/High, Severity/Critical, Type/Bug
