### ISSUE TITLE
Block adding the same properties in an annotation more than once

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3367] opened 2017-10-09 08:01 UTC
![prop](https://user-images.githubusercontent.com/1845370/31329097-1d569470-acf6-11e7-9cd5-368311afc85b.png)

**Comment by NatashaWso2** [comment] 2017-11-16 17:57
This is a duplicate of #2100, hence closing this issue.

**Closed by NatashaWso2** 2017-11-16 17:57 UTC
Labels: Priority/High, Severity/Minor, Type/Bug
