### ISSUE TITLE
No suggestions for content-types in try-it

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4405] opened 2017-11-04 03:12 UTC
![3](https://user-images.githubusercontent.com/1845370/32401774-f468bfca-c13b-11e7-9bb9-cbd8b49ac202.png)

**Comment by hemikak** [comment] 2017-11-09 10:40
Duplicate of https://github.com/ballerinalang/composer/issues/3684

**Closed** 2017-11-09 11:43 UTC
Labels: 0.95, Priority/High, Resolution/Duplicate, Severity/Minor, Type/Improvement
