### ISSUE TITLE
Settings feature in the editor does not work

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2782] opened 2017-08-17 05:08 UTC
Release - 0.92

Changing settings (both font size and color) does not have any effect on the composer

**Comment by pahans** [comment] 2017-09-07 08:57
duplicate of https://github.com/ballerinalang/composer/issues/2571
closing in favor of https://github.com/ballerinalang/composer/issues/2571

**Closed by pahans** 2017-09-07 08:57 UTC
Labels: Bug, Priority:High, Severity:Minor
