### ISSUE TITLE
Text inside the assignment dialog doesn't get cleared when deleted

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3400] opened 2017-10-09 13:06 UTC
Version: 0.93
Browser: Chrome Version 61.0.3163.100

**Steps**
1. Drop in an assignment box
2. Write down a statement. E.g. `string a = "sample"`
3. Press enter
4. Reselect the box
5. Clear the text by backspace or select & delete

**Actual behavior**
After deleting when the mouse if placed outside of the box, the deleted text reappears

**Expected behaviour**
When the user deletes the text in the box, it should be set to the default text that is there in the assignment box

**Comment by nadeeshaan** [comment] 2017-10-25 12:27
This is by design. The intention here is if the provided content is invalid then the most previous content will be fed into the statement. Assume a scenario, that the user mistakenly deletes the whole content and click outside. Reverting back to the default is not the viable option for such cases. Hence we stick to this implementation by design. Hence closing the issue

**Closed by nadeeshaan** 2017-10-25 12:27 UTC
Labels: Type/Bug, Type/UX
