### ISSUE TITLE
A statement for struct initialization appears in multiple lines in source view

### ISSUE THREAD

**Issue by kavithasub** [ballerinalang/composer#736] opened 2017-02-16 10:00 UTC
Using build from master 16-Feb (36675f2b982cd688afae1c8e9f4ff626a373092a)
Also if I corrected from source view and do below:
1. Navigate to design : Error popup and log prints[1] 

2. Try Code-> "Refactor code" : again back to multiple line

[1] 
2017-02-16 15:37:24,914 ERROR - error: <unknown>:18:0: unwanted token 'typeconvertor'

![struct1](https://cloud.githubusercontent.com/assets/15671620/23016487/ac37e7f0-f45c-11e6-9b6e-54df0d28a6ea.jpeg)
![struct2](https://cloud.githubusercontent.com/assets/15671620/23016492/ae427f6a-f45c-11e6-8b9b-0c2fd77c5970.jpeg)

**Comment by kaviththiranga** [comment] 2017-06-23 10:12
This is fixed with the changes for new approach of source formatting based on AST (vs token base). Cannot reproduce on master.

**Closed by kaviththiranga** 2017-06-23 10:12 UTC
Labels: enhancement, Source-View
