### ISSUE TITLE
[Firefox] Eventhough transaction block is deleted from source, it's not removed from designer view

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3796] opened 2017-10-16 16:26 UTC
Browser: Firefox 56.0 (64-bit)

**Steps**
1. Drop in a transaction block inside a function
2. Delete the other blocks except transaction block
3. Delete the transaction block from the source view

Although deleted from source view, the change does not get affected to the design view.

![com_0 94_firefox_1](https://user-images.githubusercontent.com/15624590/31623323-b3fce836-b2bc-11e7-87d1-4b6ec67e2715.png)

![com_0 94_firefox_2](https://user-images.githubusercontent.com/15624590/31623337-ba378e9a-b2bc-11e7-8e96-f57548ff937b.png)

**Comment by nadeeshaan** [comment] 2017-10-18 10:05
Cannot reproduce in the master. Please reopen if this is still reproducible. Hence closing the issue

**Closed by nadeeshaan** 2017-10-18 10:05 UTC
Labels: 0.94-pre-release, Priority/Highest, Severity/Critical
