### ISSUE TITLE
Global search needs to support patterns 

### ISSUE THREAD

**Issue by dakshika** [ballerinalang/composer#3045] opened 2017-09-12 01:15 UTC
When user try to use facebook or any other connector they will first type term "facebook" instead of method such as "likes". Shall we incorporate to serve results for terms such as "facebook like" ?

**Comment by NatashaWso2** [comment] 2017-11-21 12:42
This is a duplicate of #2115, hence this issue can be closed.

**Closed by NatashaWso2** 2017-11-21 12:42 UTC
Labels: Type/Improvement
