### ISSUE TITLE
Address already in use: bind

### ISSUE THREAD

**Issue by Sumudu-Sahan** [ballerinalang/composer#2596] opened 2017-07-22 08:31 UTC
When the system will move to the idle state for few hours, this error will automatically comes out and cannot execute the program.

`ballerina: address already in use: bind`

**Comment by pahans** [comment] 2017-07-25 08:53
duplicate of https://github.com/ballerinalang/composer/issues/2229

**Closed by pahans** 2017-07-25 08:53 UTC
