### ISSUE TITLE
typemapper should support to add empty struct initialization and drag-drop a return statement via graphical

### ISSUE THREAD

**Issue by kavithasub** [ballerinalang/composer#747] opened 2017-02-16 12:56 UTC
- Add two structs
- Add a typemapper and map above structs
- After variables mapped in the graphical view, it will appears in source as below example[1]

Issue1: with the null initialization for struct (e.g. stud x;) in typemapper is giving an runtime error[2]
Suggestion: initialization for struct should be added with empty value (e.g. stud x = {};)

Issue2: Drag and drop 'return' inside the typemapper is not supporting now

[1]
![struct4](https://cloud.githubusercontent.com/assets/15671620/23022005/b9420bc0-f474-11e6-92d6-96a6c27a5de5.jpeg)

[2] 
error in ballerina program: field 'x' is null

**Comment by TanyaM** [comment] 2017-02-23 06:08
Issue 1 : This is fixed in the RC2 

Issue 2 : Return statement is added to the AST at the time of dragging and dropping a type mapper from the tool palette. Hence user need not to explicitly add a return. Therefore it is not allowed to drop another return to the type mapper canvas.

**Comment by nadeeshaan** [comment] 2017-03-29 05:44
According to the above comment, issue has been fixed described in 1 and the Issue 2 is the expected behavior since the return type is by default added. Tested in the latest master and hence closing

**Closed by nadeeshaan** 2017-03-29 05:44 UTC
Labels: bug
