### ISSUE TITLE
Valid temp variables added get removed from the transform view

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3650] opened 2017-10-12 13:53 UTC
Valid temp variables added get removed from the transform view except strings
1. Add a temp variable from the source
2. Change the value to int i = 5 and add

**Issue**
This is getting removed from the transform view once added. But, can see the variable in the source view

**Comment by keizer619** [comment] 2017-10-20 08:27
This cannot reproduce in latest pack. Hence i am closing this issue

**Closed by keizer619** 2017-10-20 08:27 UTC
Labels: 0.94-pre-release, Priority/High, Severity/Major, Transform Stmt, Type/Bug
