### ISSUE TITLE
Footer is not adjusting when Design view zoom out in Safari

### ISSUE THREAD

**Issue by lahirus** [ballerinalang/composer#2034] opened 2017-06-21 00:18 UTC
<img width="764" alt="screen shot 2017-06-20 at 7 17 42 pm" src="https://user-images.githubusercontent.com/3665108/27361486-44162400-55ed-11e7-9e23-77cdc5981ac3.png">

**Comment by hevayo** [comment] 2017-06-21 05:08
Duplicate of #877

**Closed by hevayo** 2017-06-21 05:08 UTC
