### ISSUE TITLE
Newly initialized structs/maps/json types are not reflected in the source list

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3791] opened 2017-10-16 16:07 UTC
1. In the split view, initialized a struct/json/map type
2. Check the source list

**Issue**
Does not show these in the source list. Need to go back to the design view and come back to make them available in the list

**Comment by keizer619** [comment] 2017-10-17 09:04
We have analyzed the root cause, it same as following issue [1] where as non-literal variable definitions are not loaded for transform inputs. This will result avoiding JSON, XML and structs. Hence i am closing this issue and continue the following issue.

[1] https://github.com/ballerinalang/composer/issues/3657

**Closed by keizer619** 2017-10-17 09:04 UTC
Labels: 0.94-pre-release, Priority/High, Severity/Major, Transform Stmt, Type/Bug
