### ISSUE TITLE
[Editor] Automatically creating the connections between connectors

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/composer#326] opened 2017-02-09 13:23 UTC
<a href="https://github.com/dilinisg"><img src="https://avatars.githubusercontent.com/u/1845370?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Tuesday Feb 07, 2017 at 11:23 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1540_

----

1. Add a service
2. Add two HTTP connectors
3. Add HTTP actions

Issue
The connection will be automatically created with the second connector and cannot change it

![conn](https://cloud.githubusercontent.com/assets/1845370/22689271/30e02728-ed56-11e6-8942-816abb29f355.png)

**Comment by nadeeshaan** [comment] 2017-03-24 08:25
closing based on the last comment and in the latest master this issue cannot reproduce

**Closed by nadeeshaan** 2017-03-24 08:25 UTC
Labels: Imported
