### ISSUE TITLE
Too much space in the Compact view compared to the Default view

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2937] opened 2017-08-28 11:29 UTC
Release 0.93

Compact view is not consistent with the Default view,

- The boxes are centered
- No white space

![center](https://user-images.githubusercontent.com/1845370/29771429-490b10d8-8c11-11e7-958f-d249905e0518.png)

In the compact view,
- Text is left aligned
- Too much space on right

![space](https://user-images.githubusercontent.com/1845370/29771508-cb9b52e2-8c11-11e7-80e8-00d11cfbf3a1.png)

**Comment by nadeeshaan** [comment] 2017-09-09 07:55
This is enforced by design. The idea here is to provide a source view like feeling to the user. Hence closing the issue

**Closed by nadeeshaan** 2017-09-09 07:55 UTC
Labels: Enhancement, Priority:High
