### ISSUE TITLE
No values will be set to request and response when debugging a service

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4450] opened 2017-11-04 13:20 UTC
![27](https://user-images.githubusercontent.com/1845370/32405738-00426c92-c191-11e7-93e9-3301f44d69d2.png)

**Comment by pahans** [comment] 2017-11-23 08:22
duplicate of https://github.com/ballerinalang/composer/issues/4474

**Closed by pahans** 2017-11-23 08:22 UTC
Labels: 0.95, Priority/High, Severity/Major, Type/Bug
