### ISSUE TITLE
Single quotes are not supported in expression editor

### ISSUE THREAD

**Issue by dakshika** [ballerinalang/composer#3046] opened 2017-09-12 01:17 UTC
When you try to add string with single quote expression editor will automatically remove the single quotes from the string

**Comment by roonyh** [comment] 2017-11-16 06:11
Seems to be fixed in 0.95. Please reopen if reproduced.
![peek 2017-11-16 11-36](https://user-images.githubusercontent.com/3872221/32876415-c6a381c0-cac2-11e7-8621-573c9fb1916d.gif)

**Closed by roonyh** 2017-11-16 06:11 UTC
Labels: Type/Bug
