### ISSUE TITLE
[Debugger] err variables are duplicated

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/composer#2635] opened 2017-07-27 07:21 UTC
![image](https://user-images.githubusercontent.com/1029806/28658710-442be854-72ca-11e7-93be-d152e784905b.png)

**err** variable is duplicated in the frame. Check with the following service.
```
import ballerina.net.http;
import ballerina.lang.messages;
import ballerina.lang.errors;
import ballerina.lang.system;
import ballerina.lang.math;

Person[] people = [{name:"Ann", age:30, city:"London"}, {name:"Tim", age:20, city:"New York"}, {name:"John", age:25, city:"Brisbane"},
{name:"Sarah", age:10, city:"Chicago"}, {name:"Trevor", age:45, city:"Cape Town"}];

@http:configuration {
    basePath: "/people"}
service<http> PeopleManagementService {

    @http:POST {}
    @http:Path {
        value: "/update/"}
    resource updateCity (message m, @http:QueryParam{value:"index"} int index) {
        json j = messages:getJsonPayload(m);
        errors:Error err;
        var person, err = <Person> j;
        if (err != null) {
            system:print("Error 1 : ");
            system:println(err);
        }
        // json response = {};

        // transform {
        //     response.name = p.name;
        //     response.age = p.age;
        //     response.city = city;
        // }
        
        transform{
            people[index].name = person.name;
            people[index].age = person.age;
            people[index].city = person.city;
        }
        
        var response, err = <json>people[index];
        if (err != null) {
            system:print("Error 2 : ");
            system:println(err);
        }
        
        messages:setJsonPayload(m, response);
        reply m;
    }
    
    @http:GET {}
    @http:Path {
        value: "/random"}
    resource GetRandomPerson (message m) {
        int index = math:randomInRange(0, people.length);
        errors:Error err;
        var jsonPayload, err = <json> people[index];
        if (err != null) {
            var errorJson, _ = <json> err;
            messages:setJsonPayload(m, errorJson);
        } else {
            jsonPayload.index = index;
            messages:setJsonPayload(m, jsonPayload);
        }
        reply m;
    }
}

struct Person {
    string name;
    int age;
    string city;
}

```

**Comment by pahans** [comment] 2017-08-22 18:04
Duplicate of a runtime issue. Closing in favor of https://github.com/ballerinalang/ballerina/issues/2669

**Closed by pahans** 2017-08-22 18:04 UTC
Labels: Debugger
