### ISSUE TITLE
No content assist in HTTP configuration block

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3632] opened 2017-10-12 12:31 UTC
![screenshot from 2017-10-12 17-59-31](https://user-images.githubusercontent.com/7681361/31495982-4495f692-af77-11e7-93a6-efc1b22ade5a.png)

**Comment by NatashaWso2** [comment] 2017-11-21 06:53
This is a duplicate of #2369, hence this issue can be closed.

**Closed by NatashaWso2** 2017-11-21 06:53 UTC
Labels: 0.94-pre-release, Content Assist
