### ISSUE TITLE
Cannot stop running an application

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#1004] opened 2017-02-19 22:12 UTC
Freeze the browser and clicking on the button won't stop running the application

![screenshot from 2017-02-20 03-26-41](https://cloud.githubusercontent.com/assets/1845370/23107166/2497933a-f71e-11e6-8ecc-0e17cfdebf43.png)

code
```ballerina
import ballerina.lang.system;
import ballerina.lang.arrays;

function main(string[] args) {
	int i = 0;
	int[] num = [10, 20, 30, 40, 50];
	while (arrays:length(num) > i) {
		system:println("printing numbers" + num[i]);
		
	}	
}
```

**Comment by nadeeshaan** [comment] 2017-03-21 12:51
Same issue can be experienced if we run this with `./ballerina run main /path/to/bal/file`

**Comment by pahans** [comment] 2017-08-10 11:45
Root cause to this issue is while using `println` in a infinite loop console tries to render every time it receive a new line to print. According to current implementation for console this is a huge DOM manipulation Because it deletes all DOM nodes and recreates those again with the new DOM node for new `println` line. Above temporary fix will handle around 5000 iterations. Migrating console component in to a react component is the concrete solution.

**Comment by pahans** [comment] 2017-10-25 21:05
duplicate of https://github.com/ballerinalang/composer/issues/3599. Closing this because the latter describes the issue better

**Closed by pahans** 2017-10-25 21:05 UTC
Labels: Type/Bug
