### ISSUE TITLE
[Debugger] Cannot reconnect to server after connecting once

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3879] opened 2017-10-17 04:43 UTC
When reconnecting the composer to ballerina server for a debug session, it gives the following error.
![screenshot from 2017-10-17 10-09-48](https://user-images.githubusercontent.com/7681361/31647086-a70733d6-b323-11e7-8733-86adb4165941.png)

**Comment by pahans** [comment] 2017-10-17 14:18
This happens due to an issue in ballerina core. ballerina files do not finish executing when debugging. the issue is fixed in latest ballerina core.

**Closed by pahans** 2017-10-17 14:18 UTC
Labels: 0.94-pre-release, Priority/Highest, Severity/Blocker
