### ISSUE TITLE
For a file that is freshly created, save from menu and ctrl+s have different behaviours

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3347] opened 2017-10-09 05:24 UTC
Version: 0.93
Browser: Chrome Version 61.0.3163.100

**Steps**
1. Create a new file
2. Press ctrl+s 

At this point, if tried to save from selecting the option from the menu, then the option is disabled. But from keyboard short cut the option is opened and the user is able to save (save button enabled)

There should be a common path for both these cases. That is

IF file is "new"
THEN save enable or disabled (has to reflect from both UI and keyboard short cut)

**Comment by dakshika** [comment] 2017-10-25 11:16
Cannot reproduce on latest master hence closing the issue

**Closed by dakshika** 2017-10-25 11:16 UTC
Labels: Type/UX
