### ISSUE TITLE
The tool pallet hangs when more than one type mapper is added to the design

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#987] opened 2017-02-19 19:22 UTC
1. Try to add more than one type mapper to the canvas

Issue
At a time the pointer will be like in the screen shot and won't be able to add any construct until refresh the page
![structs222](https://cloud.githubusercontent.com/assets/1845370/23105524/c95d0f34-f706-11e6-8f1b-a22524839993.png)

**Comment by nadeeshaan** [comment] 2017-03-28 04:28
Could not reproduce the issue in the latest master. Hence closing the issue.

**Closed by nadeeshaan** 2017-03-28 04:28 UTC
Labels: bug
