### ISSUE TITLE
Comments are not recongized when defined sameline with the IF clause

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3456] opened 2017-10-10 09:26 UTC
Version: 0.93
Browser: Chrome Version 61.0.3163.100

As shown in the attached image when the comment is defined in the same line with the IF clause it's not recognized as a comment

![composer_comment](https://user-images.githubusercontent.com/15624590/31379146-19e1cff0-adcb-11e7-8fc2-ccb7be5c8b01.png)

**Comment by hevayo** [comment] 2017-11-24 06:12
Duplicate of https://github.com/ballerinalang/composer/issues/2065

**Closed by hevayo** 2017-11-24 06:12 UTC
Labels: Type/Bug
