### ISSUE TITLE
Workers are not supported in the Editor

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#756] opened 2017-02-16 16:16 UTC
commit 36675f2b982cd688afae1c8e9f4ff626a373092a

1. Add a service from the design view
2. Add a worker from the design view
3. Switch to the source view and write the logic inside the worker
4. Switch to the design view

Issue
The worker will be removed from the design view. The code will also be removed when switched back to the source view. Same applies to workers inside main methods.

**Comment by nadeeshaan** [comment] 2017-03-30 13:37
Worker support has been finalized at the composer and the issue is no longer reproducible. hence closing.

**Closed by nadeeshaan** 2017-03-30 13:37 UTC
Labels: Blocker, bug
