### ISSUE TITLE
some keys are typed multiple times by the composer [0.89]

### ISSUE THREAD

**Issue by shavantha** [ballerinalang/composer#2262] opened 2017-07-04 04:56 UTC
some keys are typed multiple times by the composer.

steps
1.attempt to type import statement.

the composer types the keys multiple times

workaround is to copy past the words to overcome the issue
![wording](https://user-images.githubusercontent.com/6552100/27815613-12a5087c-6075-11e7-8b56-f126518d1226.png)
Note: check the last import statement of the attached image

**Comment by pahans** [comment] 2017-07-04 04:57
possibly duplicate of https://github.com/ballerinalang/composer/issues/2235

**Comment by nadeeshaan** [comment] 2017-07-24 09:53
Fixed with 1660cef97f009c021e7fae18f0f52345dfa25965 hence closing the issue

**Closed by nadeeshaan** 2017-07-24 09:53 UTC
Labels: Severity:Blocker
